kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:        # <- corrected this line
    requests:
      storage: 1Gi
  storageClassName: local-storage
